export default [
    "Count your life by smiles, not tears. Count your age by friends, not years. Happy birthday!",
    "A wish for you on your birthday, whatever you ask may you receive, whatever you seek may you find, whatever you wish may it be fulfilled on your birthday and always. Happy birthday!",
    "Happy birthday! I hope all your birthday wishes and dreams come true.",
    "Another adventure filled year awaits you. Welcome it by celebrating your birthday with pomp and splendor. Wishing you a very happy and fun-filled birthday!",
    "May the joy that you have spread in the past come back to you on this day. Wishing you a very happy birthday!",
    "Happy birthday! Your life is just about to pick up speed and blast off into the stratosphere. Wear a seat belt and be sure to enjoy the journey. Happy birthday!",
    "This birthday, I wish you abundant happiness and love. May all your dreams turn into reality and may lady luck visit your home today. Happy birthday to one of the sweetest people I’ve ever known.",
    "May you be gifted with life’s biggest joys and never-ending bliss. After all, you yourself are a gift to earth, so you deserve the best. Happy birthday.",
    "Count not the candles…see the lights they give. Count not the years, but the life you live. Wishing you a wonderful time ahead. Happy birthday.",
    "Forget the past; look forward to the future, for the best things are yet to come.",
    "Birthdays are a new start, a fresh beginning and a time to pursue new endeavors with new goals. Move forward with confidence and courage. You are a very special person. May today and all of your days be amazing!",
    "Your birthday is the first day of another 365-day journey. Be the shining thread in the beautiful tapestry of the world to make this year the best ever. Enjoy the ride.",
    "Be happy! Today is the day you were brought into this world to be a blessing and inspiration to the people around you! You are a wonderful person! May you be given more birthdays to fulfill all of your dreams!",
    "Happy birthday! May your Facebook wall be filled with messages from people you never talk to.",
    "You’re older today than yesterday but younger than tomorrow, happy birthday!",
    "Forget about the past, you can’t change it. Forget about the future, you can’t predict it. And forget about the present, I didn’t get you one. Happy birthday!",
    "Cheers on your birthday. One step closer to adult underpants.",
    "Happy birthday to one of the few people whose birthday I can remember without a Facebook reminder.",
    "Happy Birthday! You know, you don’t look that old. But then, you don’t look that young, either.",
    "Happy birthday to someone who is smart, gorgeous, funny and reminds me a lot of myself… from one fabulous chick to another!",
    "Don’t get all weird about getting older! Our age is merely the number of years the world has been enjoying us!",
    "As you get older three things happen. The first is your memory goes, and I can’t remember the other two. Happy birthday!",
    "To quote Shakespeare: ‘Party thine ass off!’",
    "You are only young once, but you can be immature for a lifetime. Happy birthday!",
    "On your birthday, I thought of giving you the cutest gift in the world. But then I realized that is not possible because you yourself are the cutest gift in the world.",
    "Happy birthday to someone who is forever young!",
    "It’s birthday time again, and wow! You’re a whole year older now! So clown around and have some fun to make this birthday your best one. Happy birthday!",
    "Just wanted to be the first one to wish you happy birthday so I can feel superior to your other well-wishers. So, happy birthday!",
    "Congratulations on being even more experienced. I’m not sure what you learned this year, but every experience transforms us into the people we are today. Happy birthday!",
    "When the little kids ask how old you are at your party, you should go ahead and tell them. While they’re distracted trying to count that high, you can steal a bite of their cake! Happy birthday!",
    "Wishing you a day filled with happiness and a year filled with joy. Happy birthday!",
    "Sending you smiles for every moment of your special day…Have a wonderful time and a very happy birthday!",
    "Hope your special day brings you all that your heart desires! Here’s wishing you a day full of pleasant surprises! Happy birthday!",
    "On your birthday we wish for you that whatever you want most in life it comes to you just the way you imagined it or better. Happy birthday!",
    "Sending your way a bouquet of happiness…To wish you a very happy birthday!",
    "Wishing you a beautiful day with good health and happiness forever. Happy birthday!",
    "It’s a smile from me… To wish you a day that brings the same kind of happiness and joy that you bring to me. Happy birthday!",
    "On this wonderful day, I wish you the best that life has to offer! Happy birthday!",
    "I may not be by your side celebrating your special day with you, but I want you to know that I’m thinking of you and wishing you a wonderful birthday.",
    "I wish for all of your wishes to come true. Happy birthday!",
    "Many years ago on this day, God decided to send an angel to earth. The angel was meant to touch lives and that happened! Happy birthday my sweet angel!",
    "Sending you a birthday wish wrapped with all my love. Have a very happy birthday!",
    " Happy birthday to you. From good friends and true, from old friends and new, may good luck go with you and happiness too!",
    "A simple celebration, a gathering of friends; here wishing you great happiness and a joy that never ends.",
    "It’s always a treat to wish happy birthday to someone so sweet.",
    "Happy birthday to one of my best friends. Here’s to another year of laughing at our own jokes and keeping each other sane! Love you and happy birthday!",
    "On this special day, I raise a toast to you and your life. Happy birthday.",
    "You look younger than ever! Happy birthday!",
    "Words alone are not enough to express how happy I am you are celebrating another year of your life! My wish for you on your birthday is that you are, and will always be, happy and healthy. Don’t ever change! Happy birthday my dear.",
    "I can’t believe how lucky I am to have found a friend like you. You make every day of my life so special. It’s my goal to make sure your birthday is one of the most special days ever. I can’t wait to celebrate with you!",
    "A friend like you is more priceless than the most beautiful diamond. You are not only strong and wise, but kind and thoughtful as well. Your birthday is the perfect opportunity to show you how much I care and how grateful I am to have you in my life. Happy birthday!",
    "I hope that today, at your party, you dance and others sing as you celebrate with joy your best birthday.",
    "Hope your birthday is just like you…totally freaking awesome.",
    "Wishing you a birthday that’s just as wonderful as you are!",
    "Everybody has birthdays. You just wear yours better than most!",
    "You were born, and the world became a better place.",
    "You’re not older – you’re just more distinguished.",
    "I am blessed to have a buddy like you. Happy birthday, dear friend. May your special day be loaded with happiness and love.",
    "Today is your day, live it like you are the king of the world and don’t mind what others say, this day is just for you! Happy birthday.",
    "Best wishes on your birthday! May you have maximum fun today, and minimum hangover tomorrow!",
    "Just like a fine wine, you seem to get better with age. Happy birthday, handsome guy!",
    "Hey Birthday Boy! I’m sending you this ironic birthday wish because I know you’re way too cool for ordinary human sentiments.",
    "Sending some love to the most charming man in my life. You always bring the best out of me. I do not know how you do it, but I love you for that. Happy Birthday.",
    "Happy Birthday to a great guy! You do so much for others. I hope you can take some time for yourself on your big day. You deserve it as much as anyone, and more than most.",
    "Hope all your birthday wishes come true!",
    "It’s your special day — get out there and celebrate!",
    "Wishing you the biggest slice of happy today.",
    "I hope your celebration gives you many happy memories!",
    "Our age is merely the number of years the world has been enjoying us!",
    "Enjoy your special day.",
    "Have the best birthday ever!",
    "Wherever the year ahead takes you, I hope it’s happy.",
    "The day is all yours — have fun!",
    "Happy birthday to my ride or die. Love you bunches!",
    "Thinking of you on your birthday and wishing you everything happy.",
    "Best wishes on your birthday – may you have many, many more.",
    "Cheers to you for another trip around the sun!",
    "Today is about you. I can’t wait to celebrate you all day long!",
    "Happy birthday! Here’s to more life, love, and adventures with you to come!",
    "Here's to another year of friendship, laughter, and getting up to no good together! Happy Birthday!",
    "Sending you so much love on your birthday, BFF!",
    "Feeling so grateful you entered my life when you did. Have the best day, darling.",
    "Happy birthday to the beautiful, intelligent, charming person I call my best friend!",
    "I hope you have the most fabulous celebration on this special day!",
    "I hope your day is as fabulous as you are! Much love and many smooches.",
    "How lucky I am to grow up alongside such a caring, kind, goofy person. I hope you spend the day in good company!",
    "Wowee, another loop around the sun. HAPPY BIRTHDAY!!",
    "Today is the day! Hope you spend it pampered and in good company.",
    "I wish you a beautiful year of good friends, love, art, and incredible food. Love you!",
    "Happy birthday! Hope you have a warm day, I'm thinking of you always, and I'll see you soon!",
    "Adore you to the moon and back!",
    "It's always your day in my book, but this one is extra special.",
    "My resolution for your next trip around the sun is even more bestie time!",
    "Happiest of days to the most important person in my life. Love you!",
    "Eternally grateful for your friendship, guidance, and humor.",
    "You know the drill—happiest of birthdays to my person!",
    "You warm my heart every time I see you. Wishing you a day of joy.",
    "Thank you for always giving great advice and never blaming me when I don't take it!",
    "Wishing you a day as special as you are.",
    "Happiest of birthdays to the most special person in the room!",
    "Congrats on another trip around the sun! I hope this day is full of cake, memories, and fun.",
    "To the sweetest berry in the bunch, a very happy birthday!",
    "I hope you know how much you're loved today, best friend!",
    "I can't wait to spend the night celebrating my favorite person! I adore you to bits!",
    "Thank GOODNESS my bestie entered the world today!",
    "Wishing you the happiest of birthdays, and another amazing year around the sun by your side!",
    "You are so loved today and every day. Happy Birthday!",
    "I hope your birthday is as special as you are, friend.",
    "I can't wait to celebrate you all day long!",
    "Here's to the birthday queen/king today!",
    "I'm so grateful to celebrate another birthday with you my best friend.",
    "Ready to hit the town and let the world know it's my best friend's birthday!",
    "HBD to my BFF for life, I don't know what I'd do without you!",
    "The world got a little bit better on this day because my best friend was born!",
    "Happy Birthday to a best friend who is like no other.",
    "I hope you're enjoying your special day doing whatever it is you want!",
    "Today I'm shouting from the rooftops that it's my best friend's birthday, hooray!"
]
